version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: "America/Buenos_Aires"
  open-pull-requests-limit: 10
  allow:
    - dependency-name: "@dcl/*"
    - dependency-name: "@well-known-components/*"
    - dependency-name: "dcl-*"
  versioning-strategy: auto
