on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '34 11 * * 0'

name: Periodic validation
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: typescript
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main
      - name: clean
        run:  make clean

      - name: install
        run:  npm ci

      - name: build & test
        run:  make ci

      - name: print diff if failed
        if: ${{ failure() }}
        run: cp dist/temp/eth-connect.api.md report/eth-connect.api.md && git diff

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
